users:
  - user: 2009
    pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQBgLTroBpdGvl2u8q1gA5F5uMAfAsRF7rm98j+T+09
    repo: TAM

  - user: slim7
    pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAPospzYI5k3yYs31nSwMcnxHlZzitkbrgm+41u+T+s7
    repo: TAM

  - user: zzdroide
    pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJj3bsznqRyayDRW9pP7hmv35GR4H/u0Svt6zN0+zzd
    repo: TAM

  - user: AMGS
    pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG6uWdjRprcxBp3kXqUcf9kJ9De/qDe34BDk6XnRVSkG
    repo: AMGS
