[tool.poetry]
name = "tamborgcont"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.9"
ansible-core = "^2.13.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
flake8 = "^5.0.4"
ansible-lint = "^6.8.0"
molecule = "^4.0.1"
molecule-vagrant = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
