- name: Add PAM hook script
  ansible.builtin.copy:
    src: files/ssh_pam_hook.sh
    dest: /usr/local/lib/
    force: false  # Don't overwrite existing
    mode: "0744"

- name: Disable MOTD in PAM
  ansible.builtin.replace:
    path: /etc/pam.d/sshd
    regexp: ^([^#].+\spam_motd.so\s)
    replace: "#\\1"

- name: Disable poweroff with power button
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?HandlePowerKey="
    line: "HandlePowerKey=ignore"
  register: logind_edit

- name: Restart systemd-logind
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted
  when: logind_edit.changed

- name: Set PAM to call hook
  # Reference: https://www.redpill-linpro.com/sysadvent/2017/12/11/break-the-glass.html
  ansible.builtin.lineinfile:
    # Using lineinfile just to prettily insert lines at the end.
    path: /etc/pam.d/sshd
    line: "{{ item.line }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
  loop:
    - line: "{{ line3 }}"
    - line: "{{ line2 }}"
      insertbefore: "{{ line3 }}"
    - line: "{{ line1 }}"
      insertbefore: "{{ line2 }}"
  vars:
    line1: " "
    line2: "# tamborgcont hook"
    line3: session required pam_exec.so quiet stdout /usr/local/lib/ssh_pam_hook.sh

- name: Symlink ssh PAM config to hpnssh
  ansible.builtin.file:
    state: link
    src: /etc/pam.d/sshd
    dest: /etc/pam.d/hpnsshd

- name: Copy tamborg-release-lock.service
  ansible.builtin.copy:
    src: files/tamborg-release-lock.service
    dest: /etc/systemd/system/
    force: false  # Don't overwrite existing
    owner: root
    group: root
    mode: "0644"

- name: Enable tamborg-release-lock.service
  ansible.builtin.systemd:
    name: tamborg-release-lock.service
    enabled: true
