- name: Copy hpnssh config
  ansible.builtin.copy:
    src: files/sshd_config
    dest: /etc/hpnssh/sshd_config
    force: false  # Don't overwrite existing
    owner: root
    group: root
    mode: "0644"
  become: true
  register: hpnssh_config

- name: Restart hpnssh
  ansible.builtin.systemd_service:
    name: hpnssh
    state: restarted
  when: hpnssh_config.changed
  become: true
