# References:
# https://github.com/rapier1/hpn-ssh/tree/18.2.0#building-from-git
# https://github.com/rapier1/hpn-ssh/blob/18.2.0/HPNSSHInstallation.txt

# Note: now there's a PPA (https://launchpad.net/~rapier1/+archive/ubuntu/hpnssh)
# but it's currently failing with "cannot access '/run/hppnsshd': No such file or directory",
# so I'll keep building from git for now.

- name: Clone repo
  ansible.builtin.git:
    clone: true
    repo: https://github.com/rapier1/hpn-ssh
    dest: ~/hpn-ssh
    version: c868a3b35e1f1d4c0e811a66596312c464cc76e2  # 18.2.0

- name: Check if already installed
  ansible.builtin.stat:
    path: /usr/local/sbin/hpnsshd
  register: hpnstat

- name: Install hpn-ssh
  when: not hpnstat.stat.exists
  block:
    - name: Make
      ansible.builtin.shell:
        chdir: ~/hpn-ssh
        cmd: autoreconf && ./configure --with-pam && make -j"$(nproc)"
      changed_when: true

    - name: Make install
      ansible.builtin.command:
        chdir: ~/hpn-ssh
        cmd: sudo make install
      changed_when: true

    - name: Delete default config
      # So ansible.builtin.copy "overwrites" only the default config later.
      ansible.builtin.file:
        state: absent
        path: /usr/local/etc/hpnssh/sshd_config
      become: true

- name: Add priv user
  ansible.builtin.user:
    name: hpnsshd
    comment: Privilege separated HPNSSH User
    home: /run/hpnsshd
    create_home: false
    password: "!"
    shell: /sbin/nologin
    system: true
  become: true

- name: Copy config and service files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: false  # Don't overwrite existing
    owner: root
    group: root
    mode: "0644"
  loop:
    - src: files/sshd_config
      dest: /usr/local/etc/hpnssh/sshd_config
    - src: files/hpnssh-default
      dest: /etc/default/hpnssh
    - src: files/hpnssh.service
      dest: /etc/systemd/system/hpnssh.service
  become: true

- name: Enable and start service
  ansible.builtin.systemd:
    name: hpnssh.service
    state: started
    enabled: true
  become: true
