- name: Install packages
  ansible.builtin.apt:
    name:
      - curl
      - htop
      - ncdu

      - git
      - tig

      - autojump
      - zsh
    state: present
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}"
  become: true

- name: Setup users
  ansible.builtin.import_tasks: users.yml

- name: Setup zsh
  ansible.builtin.import_tasks: zsh.yml
