- name: Check that become_user is working
  ansible.builtin.command: whoami
  become: true
  become_user: nobody
  register: check_become_user
  failed_when: check_become_user.stdout != "nobody"
  # If it fails here, maybe you forgot "ANSIBLE_PIPELINING=True"
  changed_when: false

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - python3-apt
      - gnupg2
    state: present
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}"
  become: true

- name: Install packages
  ansible.builtin.apt:
    name:
      # Basic utilities
      - curl
      - htop
      - ncdu

      # Git
      - git
      - tig

      # oh-my-zsh and plugins
      - autojump
      - command-not-found
      - zsh

      # Check Wake-on-LAN
      - ethtool

      # Serve public info
      - nginx

      # pipx for packages
      - pipx

      # For systemd-python (https://github.com/systemd/python-systemd/#to-build-from-source)
      - libsystemd-dev
      - python3-dev
      - build-essential

      # To compile hpn-ssh  https://github.com/rapier1/hpn-ssh/blob/hpn-18.7.0/HPNSSHInstallation.txt#L18
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - autoconf
      - libpam0g-dev

      # To build Borg  https://borgbackup.readthedocs.io/en/stable/installation.html#debian-ubuntu
      - python3
      - python3-dev
      - libacl1-dev
      - libssl-dev
      - liblz4-dev
      - libzstd-dev
      - libxxhash-dev
      - build-essential
      - pkg-config
      - libfuse3-dev
      - fuse3

      # To manage server sleep
      - autosuspend
    state: present
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}"
  become: true

- name: Setup system
  ansible.builtin.include_tasks: system.yml
  vars:
    ansible_become: true
    iface: "{{ ansible_default_ipv4.interface }}"   # enp3s0

- name: Setup users
  ansible.builtin.import_tasks: users.yml
  vars:
    ansible_become: true

- name: Setup zsh
  ansible.builtin.import_tasks: zsh.yml
  vars:
    ansible_become: true

- name: Setup hpn-ssh
  ansible.builtin.import_tasks: hpnssh.yml

- name: Setup hook
  ansible.builtin.import_tasks: hook.yml
  vars:
    ansible_become: true

- name: Setup nginx
  ansible.builtin.import_tasks: nginx.yml
  vars:
    ansible_become: true

- name: Install Python packages
  ansible.builtin.import_tasks: python.yml
  vars:
    ansible_become: true
