- name: Install over default site
  ansible.builtin.copy:
    src: files/nginx_site
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: "0644"
    force: true  # Replace on changes
  register: site_copy

- name: Reduce nginx resource usage
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "^worker_processes "
    line: "worker_processes 1;"
  register: worker_processes

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  when: site_copy.changed or worker_processes.changed

- name: Give borg user write access
  ansible.builtin.file:
    path: /var/www/html
    owner: borg
    group: borg
    mode: "0775"

- name: Delete default index html
  ansible.builtin.file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
