- name: Install latest pipx
  ansible.builtin.pip:
    name: pipx
    state: present
    break_system_packages: true

- name: Install user packages with pipx
  become_user: borg   # noqa partial-become
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: present
    python: "{{ item.python | default(omit) }}"
  loop:
    - name: poetry
      source: poetry
    - name: borgbackup
      source: borgbackup[pyfuse3]
      python: python3.13
      # Note: there's a PPA, but it doesn't work with Debian.

  # Future, trixie: install with apt
- name: Install system packages with pipx
  community.general.pipx:
    name: autosuspend
    source: git+https://github.com/languitar/autosuspend.git@v8.0.0
    state: present
    global: true
