- name: Install user packages with pipx
  become_user: borg   # noqa partial-become
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: present
    python: "{{ item.python | default(omit) }}"
  loop:
    - name: poetry
      source: poetry
    - name: borgbackup
      source: borgbackup[pyfuse3]
      python: python3.13
      # Note: there's a PPA, but it doesn't work with Debian.
