- name: Install packages with pipx
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: present
    python: "{{ item.python | default(omit) }}"
  loop:
    - name: poetry
      source: poetry~=1.7.1
    - name: borgbackup
      source: borgbackup[pyfuse3]
      python: python3.12
      # Note: there's a PPA, but it doesn't work with Debian.

- name: Save Borg vars
  ansible.builtin.lineinfile:
    path: ~/.zprofile
    regexp: ^export BORG_REPO=
    line: export BORG_REPO="$HOME/TAM"
    state: present
    create: true
    mode: "0644"
