- name: Install pipx
  ansible.builtin.pip:
    name: pipx
    state: present

- name: Install packages with pipx
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: present
    python: "{{ item.python | default(omit) }}"
  loop:
    - name: poetry
      source: poetry~=1.7.1
    - name: borgbackup
      source: borgbackup[pyfuse3]==2.0.0b7
      python: python3.12
