- name: Create TLS directory
  ansible.builtin.file:
    path: /etc/ssl/tamborg
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create CA private key
  community.crypto.openssl_privatekey:
    path: /etc/ssl/tamborg/ca.key
    type: Ed25519
    mode: "0600"
    owner: root
    group: root

- name: Create CA certificate signing request
  community.crypto.openssl_csr:
    path: /etc/ssl/tamborg/ca.csr
    privatekey_path: /etc/ssl/tamborg/ca.key
    common_name: tamborg CA
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    mode: "0644"
    owner: root
    group: root

- name: Create self-signed CA certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/tamborg/ca.crt
    csr_path: /etc/ssl/tamborg/ca.csr
    privatekey_path: /etc/ssl/tamborg/ca.key
    provider: selfsigned
    selfsigned_not_after: "+7300d"
    mode: "0644"
    owner: root
    group: root

- name: Create leaf private keys
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/tamborg/{{ item.name }}.key"
    type: Ed25519
    mode: "0600"
    owner: root
    group: root
  loop:
    - name: tamborg_server
    - name: always_on_server

- name: Create leaf certificate signing requests
  community.crypto.openssl_csr:
    path: "/etc/ssl/tamborg/{{ item.name }}.csr"
    privatekey_path: "/etc/ssl/tamborg/{{ item.name }}.key"
    common_name: "{{ item.name }}"
    use_common_name_for_san: false
    subject_alt_name:
      - "IP:{{ item.ip }}"
    extended_key_usage:
      - serverAuth
      - clientAuth
    mode: "0644"
    owner: root
    group: root
  loop:
    - name: tamborg_server
      ip: "{{ ansible_default_ipv4.address }}"
    - name: always_on_server
      ip: "{{ always_on_server_ip }}"

- name: Sign leaf certificates with CA
  community.crypto.x509_certificate:
    path: "/etc/ssl/tamborg/{{ item.name }}.crt"
    csr_path: "/etc/ssl/tamborg/{{ item.name }}.csr"
    provider: ownca
    ownca_path: /etc/ssl/tamborg/ca.crt
    ownca_privatekey_path: /etc/ssl/tamborg/ca.key
    ownca_not_after: "+7300d"
    mode: "0644"
    owner: root
    group: root
  loop:
    - name: tamborg_server
    - name: always_on_server
