- name: Create systemd-journal-upload group
  # Static group so that the key file can have that group.
  ansible.builtin.group:
    name: systemd-journal-upload
    system: true
    state: present

- name: Create systemd-journal-upload user
  # Static user too, because with DynamicUser=yes and no user, it fails with:
  # "Failed to update dynamic user credentials: User or group with specified name already exists."
  ansible.builtin.user:
    name: systemd-journal-upload
    group: systemd-journal-upload
    home: /run/systemd
    create_home: false
    shell: /usr/sbin/nologin
    password: "!"
    system: true
    state: present

- name: Create TLS directory
  ansible.builtin.file:
    path: /etc/ssl/tamborg
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create CA private key
  community.crypto.openssl_privatekey:
    path: /etc/ssl/tamborg/ca.key
    type: Ed25519
    mode: "0600"
    owner: root
    group: root

- name: Create CA certificate signing request
  community.crypto.openssl_csr:
    path: /etc/ssl/tamborg/ca.csr
    privatekey_path: /etc/ssl/tamborg/ca.key
    common_name: tamborg CA
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    mode: "0644"
    owner: root
    group: root

- name: Create self-signed CA certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/tamborg/ca.crt
    csr_path: /etc/ssl/tamborg/ca.csr
    privatekey_path: /etc/ssl/tamborg/ca.key
    provider: selfsigned
    selfsigned_not_after: "+7300d"
    mode: "0644"
    owner: root
    group: root

- name: Create leaf private keys
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/tamborg/{{ item.name }}.key"
    type: Ed25519
    mode: "{{ item.mode }}"
    owner: root
    group: "{{ item.group }}"
  loop:
    - name: tamborg_server
      group: systemd-journal-upload
      mode: "0640"
    - name: always_on_server
      group: root
      mode: "0600"

- name: Create leaf certificate signing requests
  community.crypto.openssl_csr:
    path: "/etc/ssl/tamborg/{{ item.name }}.csr"
    privatekey_path: "/etc/ssl/tamborg/{{ item.name }}.key"
    common_name: "{{ item.name }}"
    use_common_name_for_san: false
    subject_alt_name:
      - "IP:{{ item.ip }}"
    extended_key_usage:
      - serverAuth
      - clientAuth
    mode: "0644"
    owner: root
    group: root
  loop:
    - name: tamborg_server
      ip: "{{ ansible_default_ipv4.address }}"
    - name: always_on_server
      ip: "{{ always_on_server_ip }}"

- name: Sign leaf certificates with CA
  community.crypto.x509_certificate:
    path: "/etc/ssl/tamborg/{{ item.name }}.crt"
    csr_path: "/etc/ssl/tamborg/{{ item.name }}.csr"
    provider: ownca
    ownca_path: /etc/ssl/tamborg/ca.crt
    ownca_privatekey_path: /etc/ssl/tamborg/ca.key
    ownca_not_after: "+7300d"
    mode: "0644"
    owner: root
    group: root
  loop:
    - name: tamborg_server
    - name: always_on_server

- name: Configure journal-upload
  ansible.builtin.copy:
    dest: /etc/systemd/journal-upload.conf
    content: |
      [Upload]
      URL=https://{{ always_on_server_ip }}:19532
      ServerKeyFile=/etc/ssl/tamborg/tamborg_server.key
      ServerCertificateFile=/etc/ssl/tamborg/tamborg_server.crt
      TrustedCertificateFile=/etc/ssl/tamborg/ca.crt
    owner: root
    group: root
    mode: "0644"
  register: journal_upload_conf

- name: Enable and start systemd-journal-upload
  ansible.builtin.systemd:
    name: systemd-journal-upload
    enabled: true
    state: started
    daemon_reload: true

- name: Restart systemd-journal-upload on new config
  ansible.builtin.systemd:
    name: systemd-journal-upload
    state: restarted
  when: journal_upload_conf.changed

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Ensure systemd-journal-upload started successfully
  ansible.builtin.assert:
    that:
      - "'systemd-journal-upload.service' in ansible_facts.services"
      - ansible_facts.services['systemd-journal-upload.service'].state == 'running'
    fail_msg: systemd-journal-upload is not running
