- name: Clone omz repo
  ansible.builtin.git:
    clone: true
    repo: https://github.com/zzdroide/omz
    dest: /usr/share/omz
    version: 0ac956eb8789de33ecd57f03a58f4fda4c654dea

- name: Setup .zshrc
  # https://ericsysmin.com/2019/06/20/how-to-loop-blocks-of-code-in-ansible/
  ansible.builtin.include_tasks: zsh_rc.yml
  vars:
    ansible_become: true
  loop:
    - "{{ ansible_user_id }}"
    - borg
