- name: Rewrite authorized_keys from config.ini
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: auto_silent
    update_ak__config: ../../../../../config.yml
    update_ak__file: ~/.ssh/authorized_keys

  roles:
    - update_ak
