- name: Converge
  hosts: all
  tasks:
    - name: Test update_ak
      ansible.builtin.include_role:
        name: ../../playbooks/roles/update_ak
      vars:
        update_ak__config: ../../../../../config.example.yml
        # Don't break Molecule ssh to VirtualBox:
        update_ak__file: ~/.ssh/authorized_keys-molecule

    - name: Test deploy
      ansible.builtin.include_role:
        name: ../../playbooks/roles/deploy
