dependency:
  name: shell
  command: ansible-lint

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: instance
    box: debian/bookworm64
    memory: 512 # MB
    cpus: 1

provisioner:
  name: ansible

  config_options:
    defaults:
      stdout_callback: yaml   # human-readable output
    ssh_connection:
      pipelining: true

verifier:
  name: ansible

scenario:
  create_sequence:
    # - dependency
    - create
    - prepare
  check_sequence:
    # - dependency
    # - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    # - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    # - dependency
    # - cleanup
    - destroy
  test_sequence:
    - dependency
    # - cleanup
    - destroy
    # - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
